using NewJoinerFeedbackWizard.EntityFrameworkCore;
using Xunit;

namespace NewJoinerFeedbackWizard.EntityFrameworkCore;

public class NewJoinerFeedbackWizardEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<NewJoinerFeedbackWizardEntityFrameworkCoreFixture>
{

}
