using Xunit;

namespace NewJoinerFeedbackWizard.EntityFrameworkCore;

[CollectionDefinition(NewJoinerFeedbackWizardTestConsts.CollectionDefinitionName)]
public class NewJoinerFeedbackWizardEntityFrameworkCoreCollection : ICollectionFixture<NewJoinerFeedbackWizardEntityFrameworkCoreFixture>
{

}
