using Volo.Abp;

namespace NewJoinerFeedbackWizard.EntityFrameworkCore;

public abstract class NewJoinerFeedbackWizardEntityFrameworkCoreTestBase : NewJoinerFeedbackWizardTestBase<NewJoinerFeedbackWizardEntityFrameworkCoreTestModule>
{

}
